import jsPDF from "jspdf";

/**
 * Export a chart container or canvas as PDF with title and metadata
 */
export async function exportChartAsPDF(
  title: string,
  metadata: string[],
  chartElementId?: string
) {
  const pdf = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  
  // Dark header
  pdf.setFillColor(10, 15, 26);
  pdf.rect(0, 0, 297, 30, "F");
  
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(18);
  pdf.text(title, 15, 15);
  
  pdf.setFontSize(9);
  pdf.setTextColor(160, 175, 200);
  metadata.forEach((line, i) => {
    pdf.text(line, 15, 23 + i * 4);
  });

  // Try to capture chart as image
  if (chartElementId) {
    const el = document.getElementById(chartElementId);
    if (el) {
      const svgs = el.querySelectorAll("svg.recharts-surface");
      const canvases = el.querySelectorAll("canvas");
      
      if (svgs.length > 0) {
        for (const svg of Array.from(svgs)) {
          try {
            const svgData = new XMLSerializer().serializeToString(svg);
            const canvas = document.createElement("canvas");
            const ctx = canvas.getContext("2d")!;
            const img = new Image();
            const blob = new Blob([svgData], { type: "image/svg+xml" });
            const url = URL.createObjectURL(blob);
            
            await new Promise<void>((resolve) => {
              img.onload = () => {
                canvas.width = img.width * 2;
                canvas.height = img.height * 2;
                ctx.fillStyle = "#0a0f1a";
                ctx.fillRect(0, 0, canvas.width, canvas.height);
                ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
                const imgData = canvas.toDataURL("image/png");
                pdf.addImage(imgData, "PNG", 15, 35, 267, 150);
                URL.revokeObjectURL(url);
                resolve();
              };
              img.onerror = () => {
                URL.revokeObjectURL(url);
                resolve();
              };
              img.src = url;
            });
          } catch {
            // Fallback - just export metadata
          }
        }
      } else if (canvases.length > 0) {
        let yOffset = 35;
        for (const canvas of Array.from(canvases)) {
          try {
            const imgData = canvas.toDataURL("image/png");
            pdf.addImage(imgData, "PNG", 15, yOffset, 200, 120);
            yOffset += 125;
          } catch {
            // skip
          }
        }
      }
    }
  }

  // Footer
  const pageH = pdf.internal.pageSize.getHeight();
  pdf.setFontSize(7);
  pdf.setTextColor(100, 110, 130);
  pdf.text("Generated by Quantara — Band Structure & Solid-State Physics Module", 15, pageH - 5);
  pdf.text(new Date().toISOString().split("T")[0], 260, pageH - 5);

  pdf.save(`${title.replace(/[^a-zA-Z0-9]/g, "-").toLowerCase()}.pdf`);
}
