import { useState, useMemo, useRef, useEffect } from "react";
import GlassCard from "@/components/GlassCard";
import { Slider } from "@/components/ui/slider";
import { Button } from "@/components/ui/button";
import { generateLattice, type LatticeType } from "@/lib/solidStateEngine";
import { exportChartAsPDF } from "@/lib/pdfExport";
import DerivationBlock from "./DerivationBlock";
import { Download, FileText } from "lucide-react";

const SliderRow = ({ label, value, min, max, step, onChange, unit }: {
  label: string; value: number; min: number; max: number; step: number; onChange: (v: number) => void; unit?: string;
}) => (
  <div className="space-y-1">
    <div className="flex justify-between text-xs">
      <span className="text-muted-foreground">{label}</span>
      <span className="font-mono text-primary bg-primary/10 px-1.5 rounded text-[11px]">{value.toFixed(1)}{unit}</span>
    </div>
    <Slider min={min} max={max} step={step} value={[value]} onValueChange={([v]) => onChange(v)} className="h-4" />
  </div>
);

const LATTICE_DERIVATION = [
  {
    title: "Bravais Lattice Definition",
    content: "A Bravais lattice is an infinite set of points generated by primitive translation vectors a₁ and a₂ (in 2D). Every lattice point R can be expressed as an integer linear combination of these vectors.",
    equation: "R = n₁a₁ + n₂a₂,  n₁, n₂ ∈ ℤ"
  },
  {
    title: "Square Lattice",
    content: "The simplest 2D Bravais lattice. Primitive vectors are orthogonal with equal magnitude a. Point group symmetry: C₄ᵥ. Coordination number: 4.",
    equation: "a₁ = a·x̂,  a₂ = a·ŷ  |  |a₁| = |a₂| = a,  a₁ · a₂ = 0"
  },
  {
    title: "Rectangular Lattice",
    content: "Orthogonal primitive vectors with unequal magnitudes a ≠ b. Reduced symmetry compared to square: C₂ᵥ. The unit cell area is Ω = ab.",
    equation: "a₁ = a·x̂,  a₂ = b·ŷ  |  Ω = |a₁ × a₂| = ab"
  },
  {
    title: "Honeycomb Lattice (Graphene)",
    content: "NOT a Bravais lattice — it is a triangular Bravais lattice with a 2-atom basis (sublattices A and B). The basis vectors form 60° angle. Each atom has 3 nearest neighbors.",
    equation: "a₁ = a·x̂,  a₂ = (a/2)·x̂ + (a√3/2)·ŷ  |  δ = (0, a/√3)  (basis vector)"
  },
  {
    title: "Reciprocal Lattice Construction",
    content: "The reciprocal lattice vectors b₁, b₂ satisfy a_i · b_j = 2πδ_{ij}. They are computed from the real-space vectors using the cross product formula:",
    equation: "b₁ = 2π(a₂ × ẑ) / (a₁ · (a₂ × ẑ)),  b₂ = 2π(ẑ × a₁) / (a₂ · (ẑ × a₁))"
  },
  {
    title: "Reciprocal Lattice Properties",
    content: "The reciprocal lattice of a square lattice is also square with spacing 2π/a. For a triangular lattice, the reciprocal is rotated triangular. The Wigner-Seitz cell of the reciprocal lattice defines the first Brillouin zone.",
    equation: "|b₁| = 2π/a (square),  G_{hk} = h·b₁ + k·b₂  (reciprocal lattice vector)"
  },
];

const LatticeCanvas = ({ points, vectors, width, height, title, isReciprocal }: {
  points: { x: number; y: number; sublattice?: string }[];
  vectors: { a1: [number, number]; a2: [number, number] };
  width: number; height: number; title: string; isReciprocal?: boolean;
}) => {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d")!;
    const dpr = window.devicePixelRatio || 1;
    canvas.width = width * dpr;
    canvas.height = height * dpr;
    ctx.scale(dpr, dpr);
    ctx.clearRect(0, 0, width, height);

    const allX = points.map(p => p.x);
    const allY = points.map(p => p.y);
    const rangeX = Math.max(...allX) - Math.min(...allX) || 1;
    const rangeY = Math.max(...allY) - Math.min(...allY) || 1;
    const scale = Math.min((width - 60) / rangeX, (height - 60) / rangeY);
    const cx = width / 2, cy = height / 2;
    const ox = (Math.max(...allX) + Math.min(...allX)) / 2;
    const oy = (Math.max(...allY) + Math.min(...allY)) / 2;
    const toScreen = (x: number, y: number): [number, number] => [cx + (x - ox) * scale, cy - (y - oy) * scale];

    // Grid
    ctx.strokeStyle = "hsla(222, 30%, 25%, 0.2)";
    ctx.lineWidth = 0.5;
    for (let i = 0; i <= 10; i++) {
      const x = (width / 10) * i;
      ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, height); ctx.stroke();
      ctx.beginPath(); ctx.moveTo(0, x); ctx.lineTo(width, x); ctx.stroke();
    }

    // Vectors from origin
    const [ox0, oy0] = toScreen(0, 0);
    const drawArrow = (dx: number, dy: number, color: string, label: string) => {
      const [tx, ty] = toScreen(dx, dy);
      ctx.strokeStyle = color;
      ctx.lineWidth = 2.5;
      ctx.beginPath(); ctx.moveTo(ox0, oy0); ctx.lineTo(tx, ty); ctx.stroke();
      const angle = Math.atan2(oy0 - ty, tx - ox0);
      ctx.beginPath();
      ctx.moveTo(tx, ty);
      ctx.lineTo(tx - 12 * Math.cos(angle - 0.3), ty + 12 * Math.sin(angle - 0.3));
      ctx.moveTo(tx, ty);
      ctx.lineTo(tx - 12 * Math.cos(angle + 0.3), ty + 12 * Math.sin(angle + 0.3));
      ctx.stroke();
      ctx.fillStyle = color;
      ctx.font = "bold 13px Inter";
      ctx.fillText(label, tx + 6, ty - 6);
    };
    drawArrow(vectors.a1[0], vectors.a1[1], "hsl(40, 90%, 55%)", isReciprocal ? "b₁" : "a₁");
    drawArrow(vectors.a2[0], vectors.a2[1], "hsl(150, 70%, 50%)", isReciprocal ? "b₂" : "a₂");

    // Points
    for (const p of points) {
      const [px, py] = toScreen(p.x, p.y);
      if (px < -10 || px > width + 10 || py < -10 || py > height + 10) continue;
      ctx.beginPath();
      const r = isReciprocal ? 3 : 5;
      ctx.arc(px, py, r, 0, 2 * Math.PI);

      if (p.sublattice === "B") {
        ctx.fillStyle = "hsl(350, 80%, 60%)";
      } else if (isReciprocal) {
        ctx.fillStyle = "hsl(280, 80%, 65%)";
      } else {
        ctx.fillStyle = "hsl(195, 100%, 50%)";
      }
      ctx.fill();
      ctx.strokeStyle = "hsla(0, 0%, 100%, 0.2)";
      ctx.lineWidth = 0.5;
      ctx.stroke();

      // Glow
      ctx.beginPath();
      ctx.arc(px, py, r + 3, 0, 2 * Math.PI);
      const glow = ctx.createRadialGradient(px, py, r, px, py, r + 6);
      glow.addColorStop(0, p.sublattice === "B" ? "hsla(350, 80%, 60%, 0.3)" : isReciprocal ? "hsla(280, 80%, 65%, 0.3)" : "hsla(195, 100%, 50%, 0.3)");
      glow.addColorStop(1, "transparent");
      ctx.fillStyle = glow;
      ctx.fill();
    }

    // Origin marker
    ctx.beginPath();
    ctx.arc(ox0, oy0, 3, 0, 2 * Math.PI);
    ctx.fillStyle = "#fff";
    ctx.fill();
    ctx.fillStyle = "hsl(215, 20%, 55%)";
    ctx.font = "bold 11px Inter";
    ctx.fillText("O", ox0 - 12, oy0 + 4);

    ctx.fillStyle = "hsl(215, 20%, 55%)";
    ctx.font = "11px Inter";
    ctx.fillText(title, 10, 16);
  }, [points, vectors, width, height, title, isReciprocal]);

  return <canvas ref={canvasRef} style={{ width, height }} className="rounded-lg" />;
};

export default function LatticeSimulation() {
  const [type, setType] = useState<LatticeType>("square");
  const [a, setA] = useState(2.5);
  const [b, setB] = useState(3.5);
  const [nx, setNx] = useState(4);

  const result = useMemo(() => generateLattice(type, a, b, nx, nx), [type, a, b, nx]);

  const handleExportPDF = () => {
    exportChartAsPDF(`Lattice Simulation — ${type.charAt(0).toUpperCase() + type.slice(1)}`, [
      `Type: ${type} | a = ${a} Å${type === "rectangular" ? ` | b = ${b} Å` : ""} | Grid: ${nx}×${nx}`,
      `a₁ = (${result.vectors.a1.map(v => v.toFixed(2)).join(", ")})  |  a₂ = (${result.vectors.a2.map(v => v.toFixed(2)).join(", ")})`,
      `b₁ = (${result.reciprocal.b1.map(v => v.toFixed(2)).join(", ")})  |  b₂ = (${result.reciprocal.b2.map(v => v.toFixed(2)).join(", ")})`,
    ], "lattice-vis");
  };

  return (
    <div className="space-y-4">
      <div className="grid grid-cols-1 lg:grid-cols-4 gap-4">
        <GlassCard className="p-5 space-y-4">
          <h3 className="text-sm font-semibold text-foreground">Lattice Type</h3>
          <div className="space-y-1">
            {(["square", "rectangular", "honeycomb"] as const).map(lt => (
              <button key={lt} onClick={() => setType(lt)}
                className={`w-full text-left text-xs px-3 py-2 rounded-md border transition-colors ${
                  type === lt ? "bg-primary/15 border-primary/30 text-primary font-medium" : "border-border/50 text-muted-foreground hover:bg-secondary/50"
                }`}
              >{lt.charAt(0).toUpperCase() + lt.slice(1)}{lt === "honeycomb" ? " (Graphene)" : ""}</button>
            ))}
          </div>
          <SliderRow label="a (Lattice Constant)" value={a} min={1} max={5} step={0.1} onChange={setA} unit=" Å" />
          {type === "rectangular" && (
            <SliderRow label="b (Second Constant)" value={b} min={1} max={6} step={0.1} onChange={setB} unit=" Å" />
          )}
          <SliderRow label="Grid Size" value={nx} min={2} max={8} step={1} onChange={setNx} />

          <div className="pt-3 border-t border-border/30 text-xs text-muted-foreground space-y-1">
            <p className="font-semibold text-foreground">Primitive Vectors</p>
            <p className="font-mono">a₁ = ({result.vectors.a1.map(v => v.toFixed(2)).join(", ")}) Å</p>
            <p className="font-mono">a₂ = ({result.vectors.a2.map(v => v.toFixed(2)).join(", ")}) Å</p>
            <p className="font-semibold text-foreground mt-2">Reciprocal Vectors</p>
            <p className="font-mono">b₁ = ({result.reciprocal.b1.map(v => v.toFixed(2)).join(", ")}) Å⁻¹</p>
            <p className="font-mono">b₂ = ({result.reciprocal.b2.map(v => v.toFixed(2)).join(", ")}) Å⁻¹</p>
            <p className="font-mono mt-1">Ω = {Math.abs(result.vectors.a1[0] * result.vectors.a2[1] - result.vectors.a1[1] * result.vectors.a2[0]).toFixed(2)} Å²</p>
          </div>

          <Button size="sm" variant="outline" onClick={handleExportPDF} className="gap-1.5 text-xs w-full">
            <FileText size={12} /> Export PDF
          </Button>
        </GlassCard>

        <div className="lg:col-span-3 grid grid-cols-1 md:grid-cols-2 gap-4" id="lattice-vis">
          <GlassCard className="p-4 flex flex-col items-center">
            <h3 className="text-sm font-semibold text-foreground mb-2 self-start">Real-Space Lattice</h3>
            <LatticeCanvas points={result.points} vectors={result.vectors} width={380} height={380} title="Real Space" />
            {type === "honeycomb" && (
              <div className="flex gap-4 mt-2 text-[10px]">
                <span className="flex items-center gap-1"><span className="w-2.5 h-2.5 rounded-full bg-primary" /> Sublattice A</span>
                <span className="flex items-center gap-1"><span className="w-2.5 h-2.5 rounded-full" style={{ background: "hsl(350, 80%, 60%)" }} /> Sublattice B</span>
              </div>
            )}
          </GlassCard>

          <GlassCard className="p-4 flex flex-col items-center">
            <h3 className="text-sm font-semibold text-foreground mb-2 self-start">Reciprocal Lattice</h3>
            <LatticeCanvas points={result.reciprocalPoints} vectors={{ a1: result.reciprocal.b1, a2: result.reciprocal.b2 }} width={380} height={380} title="Reciprocal Space (k-space)" isReciprocal />
          </GlassCard>
        </div>
      </div>

      {/* Derivation */}
      <DerivationBlock title="Lattice Theory & Reciprocal Space Derivation" steps={LATTICE_DERIVATION} />
    </div>
  );
}
